### ISSUE TITLE
'float' object has no attribute 'max'

### ISSUE THREAD

**Issue by nomadkml** [teese/eccpy#16]
Hi! Running your program on your test file generated_data_0.xlsx (Mac OS Big Sur, python 3.8.5) and get the following message: 'float' object has no attribute 'max'

Here are details:
AttributeError                            Traceback (most recent call last)
<ipython-input-6-e367c0b92149> in <module>
      1 settings = "/Users/nomadkml/Desktop/result/ECCpy_settings_template.xlsx"
----> 2 eccpy.run_curvefit(settings)
      3 eccpy.run_gatherer(settings)

~/opt/anaconda3/lib/python3.8/site-packages/eccpy/curvefit.py in run_curvefit(settings_excel_file)
     77         print("Starting run_curvefit program for selected samples.\n")
     78         for fn in dff.loc[dff["run curvefit"] == True].index:
---> 79             calc_EC50(fn, dff, settings, t20)
     80     else:
     81         print("None of the datafiles are marked TRUE for 'run curvefit'. Suggest checking the excel settings file.")

~/opt/anaconda3/lib/python3.8/site-packages/eccpy/curvefit.py in calc_EC50(fn, dff, settings, t20)
   1107         # set the x-axis limit so that the legend does not hide too many data points
   1108         # find the maximum dose concentration in the whole experiment for that day
-> 1109         maxAC = x_orig.max().max()
   1110         # # obtain the variable altering the extension of the x-axis
   1111         # x_axis_extension_after_dosemax_in_summ_plot = dff.loc[fn, "x-axis extension in summary fig_0"]

AttributeError: 'float' object has no attribute 'max'

**Comment by ricardo-ayres** [comment]
#17 Should solve this issue.

**Comment by teese** [comment]
I've merged #17, and the problem should be solved now.
